language: ruby
rvm:
  - 3.0.2
services:
  - postgresql
addons:
  postgresql: "12"
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
before_install:
  # FFMPEG
  - |-
    sudo apt-get update -qq && sudo apt-get -y install \
    autoconf \
    automake \
    build-essential \
    cmake \
    git-core \
    libass-dev \
    libfreetype6-dev \
    libsdl2-dev \
    libtool \
    libva-dev \
    libvdpau-dev \
    libvorbis-dev \
    libxcb1-dev \
    libxcb-shm0-dev \
    libxcb-xfixes0-dev \
    pkg-config \
    texinfo \
    wget \
    zlib1g-dev
  - mkdir -p ~/ffmpeg_sources ~/bin
  - sudo apt-get install nasm
  - sudo apt-get install yasm
  - sudo apt-get install libfdk-aac-dev
  - sudo apt-get install libmp3lame-dev
  - |-
    pushd ~/ffmpeg_sources && \
    wget -O ffmpeg-snapshot.tar.bz2 https://ffmpeg.org/releases/ffmpeg-snapshot.tar.bz2 && \
    tar xjvf ffmpeg-snapshot.tar.bz2 && \
    cd ffmpeg && \
    PATH="$HOME/bin:$PATH" PKG_CONFIG_PATH="$HOME/ffmpeg_build/lib/pkgconfig" ./configure \
      --prefix="$HOME/ffmpeg_build" \
      --pkg-config-flags="--static" \
      --extra-cflags="-I$HOME/ffmpeg_build/include" \
      --extra-ldflags="-L$HOME/ffmpeg_build/lib" \
      --extra-libs="-lpthread -lm" \
      --bindir="$HOME/bin" \
      --enable-gpl \
      --enable-libfdk-aac \
      --enable-libmp3lame \
      --enable-nonfree && \
    make && \
    make install
  - popd
  # RUBYGEMS
  - gem update --system
  - gem install bundler
before_script:
  # POSTGRESQL
  - createuser avfacts
  - createdb -O avfacts avfacts_test
  # SEED
  - bundle exec rails db:migrate webpacker:compile
env:
  global:
    - RAILS_TEST_DB_USERNAME=travis
    - PGUSER=travis
    - PGPORT=5433
    - PATH="$HOME/bin:$PATH"
script:
  - rspec spec
