shared:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  username: avfacts

development:
  database: avfacts_development

test: &test
  database: avfacts_test
  owner: avfacts
  username: <%= ENV.fetch('RAILS_TEST_DB_USERNAME') { 'tmorgan' } %>
  port: <%= ENV.fetch('PGPORT') { 5432 } %>

cypress: *test

production:
  database: avfacts_production
