shared:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  username: avfacts

development:
  database: avfacts_development

test: &test
  host: localhost
  username: <%= ENV.fetch('POSTGRES_USER') { 'tmorgan' } %>
  owner: avfacts
  password: <%= ENV.fetch('POSTGRES_PASSWORD') { '' } %>
  database: <%= ENV.fetch('POSTGRES_DB') { 'avfacts_test' } %>

cypress: *test

production:
  database: avfacts_production
