---
:concurrency: 1
:pidfile: tmp/pids/sidekiq.pid
:development:
  :queues:
    - avfacts_development_default
    - avfacts_development_active_storage_analysis
    - avfacts_development_active_storage_purge'
production:
  :concurrency: 5
  :queues:
    - avfacts_production_default
    - avfacts_production_active_storage_analysis
    - avfacts_production_active_storage_purge
