development:
  http_host: "127.0.0.1:5000"
  https: false
  frontend_url: "http://127.0.0.1:5173"
cypress:
  http_host: "127.0.0.1:5000"
  https: false
  frontend_url: "http://127.0.0.1:5173"
test:
  http_host: app.test.host
  https: false
  frontend_url: "http://test.host"
production:
  http_host: app.avfacts.org
  https: true
  frontend_url: "https://avfacts.org"
